# -*- coding: utf-8 -*-

"""
   jqlapilib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/24/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = "https://mixpanel.com/api/2.0/jql"

    # The username to use with basic authentication
    # TODO: Replace the basic_auth_user_name with an appropriate value
    basic_auth_user_name = "b498c2c2d9a11a9dd9c15efd0a1a91fe"

    # The password to use with basic authentication
    # TODO: Replace the basic_auth_password with an appropriate value
    basic_auth_password = ""


