# -*- coding: utf-8 -*-

"""
    jqlapilib.jqlapi_client

    This file was automatically generated by APIMATIC BETA v2.0 on 06/24/2016
"""

from http import *
from models import *
from controllers import *
from decorators import *
from api_exception import *

class JQLAPIClient(object):

    @lazy_property
    def jql_controller(self):
        return JQLController()


    def __init__(self, 
                 basic_auth_user_name,
                 basic_auth_password):

        Configuration.basic_auth_user_name = basic_auth_user_name
        Configuration.basic_auth_password = basic_auth_password


